import Input from './Input';
import Group from './Group';
import Search from './Search';
import TextArea from './TextArea';
import Counter from './Counter';
import './style/index.less';
Input.Group = Group;
Input.Search = Search;
Input.TextArea = TextArea;
Input.Counter = Counter;
export default Input;
