/**
 * 表单限制常量
 */
export const limit = {
  MAX_NAME_LEN: '30',
  MAX_DESC_LEN: '100',
  MAX_PWD_LEN: '16',
  MIN_PWD_LEN: '6',
  MAX_ACCOUNT_LEN: '50',
  MAX_USERNAME_LEN: '50',
  MAX_PASSWORD_LEN: '16',
  TAG_LIST_MAX_LEN: 20,
  POSITION_LIST_MAX_LEN:20,
  MAX_POSITION_LEN:1000,
  PAGE_SIZE: 50,
};
